spring:
  messages:
    basename: local/pagecontent
    encoding: UTF-8
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
  datasource:
    url: "jdbc:mysql://localhost:3306/shop-spring"
    username: "root"
    password: "1823"
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5000
      driver-class-name: "com.mysql.cj.jdbc.Driver"
server:
  port: 8081
